name: tauri-action
description: Build Tauri apps with GitHub Actions
author: remarkablemark

inputs:
  app-name:
    description: Name of your Tauri application
    required: true
  app-version:
    description: Your application version
  window-title:
    description: Window title of your Tauri application (defaults to app name)
  window-width:
    description: Window width of your Tauri application
  window-height:
    description: Window height of your Tauri application
  window-resizable:
    description: Whether the window is resizable or not
    type: boolean
  window-fullscreen:
    description: Whether the window starts as fullscreen or not
    type: boolean
  tauri-path:
    description: Path of the Tauri project to use (relative to the cwd)
  frontend-dist:
    description: Web assets location, relative to <project-dir>/src-tauri
  before-build-command:
    description: A shell command to run before `tauri build` kicks in
    default: exit 0
  force:
    description: Force init to overwrite the src-tauri folder
    type: boolean
  identifier:
    description: Bundle identifier that must be unique across applications
    default: com.${{ github.repository_owner }}.${{ github.event.repository.name }}
  tauri-version:
    description: Tauri version
    default: 2

outputs:
  bundle-path:
    description: Tauri bundle directory
    value: ${{ steps.tauri-bundle.outputs.bundle_path }}

runs:
  using: composite
  steps:
    - name: Install Tauri CLI
      shell: bash
      run: npm install --global @tauri-apps/cli@$VERSION
      env:
        VERSION: ${{ inputs.tauri-version }}

    - name: Initialize Tauri project
      shell: bash
      run: >
        tauri init
        --app-name=${{ toJSON(inputs.app-name) }}
        --window-title=${{ toJSON(inputs.window-name || inputs.app-name) }}
        ${{ inputs.frontend-dist && format('--frontend-dist={0}', toJSON(inputs.frontend-dist)) || '' }}
        --before-build-command=${{ toJSON(inputs.before-build-command) }}
        --ci
        ${{ inputs.force == 'true' && '--force' || '' }}

    - name: Update Tauri config
      shell: bash
      run: |
        CONF=src-tauri/tauri.conf.json
        TEMP=$RUNNER_TEMP/tauri.conf.json

        if [[ $VERSION ]]; then
          jq ".version = \"$VERSION\"" $CONF > $TEMP
          mv $TEMP $CONF
        fi

        if [[ $WIDTH ]]; then
          jq ".app.windows[0].width = $WIDTH" $CONF > $TEMP
          mv $TEMP $CONF
        fi

        if [[ $HEIGHT ]]; then
          jq ".app.windows[0].height = $HEIGHT" $CONF > $TEMP
          mv $TEMP $CONF
        fi

        if [[ $RESIZABLE ]]; then
          jq ".app.windows[0].resizable = $RESIZABLE" $CONF > $TEMP
          mv $TEMP $CONF
        fi

        if [[ $FULLSCREEN ]]; then
          jq ".app.windows[0].fullscreen = $FULLSCREEN" $CONF > $TEMP
          mv $TEMP $CONF
        fi

        jq '.identifier = ${{ toJSON(inputs.identifier) }}' $CONF > $TEMP
        mv $TEMP $CONF
      env:
        VERSION: ${{ inputs.app-version }}
        WIDTH: ${{ inputs.window-width }}
        HEIGHT: ${{ inputs.window-height }}
        RESIZABLE: ${{ inputs.window-resizable }}
        FULLSCREEN: ${{ inputs.window-fullscreen }}

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: >
        sudo apt-get update &&
        sudo apt-get install --yes libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Cache Rust dependencies
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build app and generate bundle
      shell: bash
      run: tauri build --ci

    - name: Output Tauri bundle path
      id: tauri-bundle
      shell: bash
      run: |
        if [[ $RUNNER_OS == 'Windows' ]]; then
          echo 'bundle_path=src-tauri\target\release\bundle' >> $GITHUB_OUTPUT
        else
          echo 'bundle_path=src-tauri/target/release/bundle' >> $GITHUB_OUTPUT
        fi

branding:
  icon: link
  color: yellow
