name: tauri-action
description: Build Tauri apps with GitHub Actions
author: remarkablemark

inputs:
  version:
    description: CLI version
    required: false
    default: 2

runs:
  using: composite
  steps:
    - name: Install Tauri CLI
      shell: bash
      run: npm install --global @tauri-apps/cli@$VERSION
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: link
  color: yellow
