name: tauri-action
description: Build Tauri apps with GitHub Actions
author: remarkablemark

inputs:
  version:
    description: Version
    required: false
    default: 1.2.3

runs:
  using: composite
  steps:
    - name: Print version
      shell: bash
      run: |
        echo "version: $VERSION"
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: link
  color: yellow
