name: tauri-action
description: Build Tauri apps with GitHub Actions
author: remarkablemark

inputs:
  app-name:
    description: Name of your Tauri application
    required: true
  window-title:
    description: Window title of your Tauri application (defaults to app name)
  tauri-path:
    description: Path of the Tauri project to use (relative to the cwd)
    default: .
  frontend-dist:
    description: Web assets location, relative to <project-dir>/src-tauri
    default: ../dist
  before-build-command:
    description: A shell command to run before `tauri build` kicks in
    default: exit 0
  force:
    description: Force init to overwrite the src-tauri folder
    default: false
  identifier:
    description: Bundle identifier that must be unique across applications
  no-sign:
    description: Skip code signing when bundling the app
    default: false
  cli-version:
    description: Tauri CLI version
    default: 2

runs:
  using: composite
  steps:
    - name: Install Tauri CLI
      shell: bash
      run: npm install --global "@tauri-apps/cli@$CLI_VERSION"
      env:
        CLI_VERSION: ${{ inputs.cli-version }}

    - name: Initialize Tauri project
      shell: bash
      run: >
        tauri init
        --app-name "$APP_NAME"
        --window-title "$WINDOW_NAME"
        --frontend-dist "$FRONTEND_DIST"
        --before-build-command "$BEFORE_BUILD_COMMAND"
        --ci
        ${{ inputs.force == 'true' && '--force' || '' }}
      env:
        APP_NAME: ${{ inputs.app-name }}
        WINDOW_NAME: ${{ inputs.window-name || inputs.app-name }}
        FRONTEND_DIST: ${{ inputs.frontend-dist }}
        BEFORE_BUILD_COMMAND: ${{ inputs.before-build-command }}

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: >
        sudo apt-get update &&
        sudo apt-get install --yes libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Cache Rust dependencies
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Set app identifier
      shell: bash
      run: |
        if [[ -z "$IDENTIFIER" ]]; then
          IDENTIFIER="com.${{ github.repository_owner }}.${GITHUB_REPOSITORY#*/}"
        fi
        TAURI_CONF=src-tauri/tauri.conf.json
        TEMP_TAURI_CONF=$RUNNER_TEMP/tauri.conf.json
        jq ".identifier = \"$IDENTIFIER\"" $TAURI_CONF > $TEMP_TAURI_CONF
        mv $TEMP_TAURI_CONF $TAURI_CONF
      env:
        IDENTIFIER: ${{ inputs.identifier }}

    - name: Build app and generate bundles
      shell: bash
      run: >
        tauri build
        --ci
        ${{ inputs.force == 'true' && '--no-sign' || '' }}

branding:
  icon: link
  color: yellow
