name: tauri-action
description: Build Tauri apps with GitHub Actions
author: remarkablemark

inputs:
  app-name:
    description: Name of your Tauri application
    required: true
  app-version:
    description: Your application version
    default: 0.1.0
  window-title:
    description: Window title of your Tauri application (defaults to app name)
  window-width:
    description: Window width of your Tauri application
    default: 800
  window-height:
    description: Window height of your Tauri application
    default: 600
  tauri-path:
    description: Path of the Tauri project to use (relative to the cwd)
    default: .
  frontend-dist:
    description: Web assets location, relative to <project-dir>/src-tauri
    default: ../dist
  before-build-command:
    description: A shell command to run before `tauri build` kicks in
    default: exit 0
  force:
    description: Force init to overwrite the src-tauri folder
    default: false
  identifier:
    description: Bundle identifier that must be unique across applications
  tauri-version:
    description: Tauri version
    default: 2

outputs:
  bundle-path:
    description: Tauri bundle directory
    value: ${{ steps.tauri-bundle.outputs.bundle_path }}

runs:
  using: composite
  steps:
    - name: Install Tauri CLI
      shell: bash
      run: npm install --global @tauri-apps/cli@$VERSION
      env:
        VERSION: ${{ inputs.tauri-version }}

    - name: Initialize Tauri project
      shell: bash
      run: >
        tauri init
        --app-name "$APP_NAME"
        --window-title "$WINDOW_NAME"
        --frontend-dist "$FRONTEND_DIST"
        --before-build-command "$BEFORE_BUILD_COMMAND"
        --ci
        ${{ inputs.force == 'true' && '--force' || '' }}
      env:
        APP_NAME: ${{ inputs.app-name }}
        WINDOW_NAME: ${{ inputs.window-name || inputs.app-name }}
        FRONTEND_DIST: ${{ inputs.frontend-dist }}
        BEFORE_BUILD_COMMAND: ${{ inputs.before-build-command }}

    - name: Update Tauri config
      shell: bash
      run: |
        if [[ -z "$IDENTIFIER" ]]; then
          IDENTIFIER="com.${{ github.repository_owner }}.${GITHUB_REPOSITORY#*/}"
        fi

        jq \
          --arg version $VERSION \
          --arg identifier $IDENTIFIER \
          --argjson width $WIDTH \
          --argjson height $HEIGHT \
          '.version = $version | .identifier = $identifier | .app.windows[0].width = $width | .app.windows[0].height = $height' \
          $TAURI_CONF > $TEMP_TAURI_CONF

        mv $TEMP_TAURI_CONF $TAURI_CONF
      env:
        VERSION: ${{ inputs.app-version }}
        IDENTIFIER: ${{ inputs.identifier }}
        WIDTH: ${{ inputs.window-width }}
        HEIGHT: ${{ inputs.window-height }}
        TAURI_CONF: src-tauri/tauri.conf.json
        TEMP_TAURI_CONF: ${{ runner.temp }}/tauri.conf.json

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: >
        sudo apt-get update &&
        sudo apt-get install --yes libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Cache Rust dependencies
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build app and generate bundle
      shell: bash
      run: tauri build --ci

    - name: Output Tauri bundle path
      id: tauri-bundle
      shell: bash
      run: echo "bundle_path=$(realpath src-tauri/target/release/bundle)" >> $GITHUB_OUTPUT

branding:
  icon: link
  color: yellow
